# Generated by Django 4.2.26 on 2025-12-29 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBakarKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapasitas', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('harga_per_hari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kendaraan/')),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Disewa', 'Sedang Disewa'), ('Perawatan', 'Dalam Perawatan')], default='Tersedia', max_length=20)),
                ('bahan_bakar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_rental.bahanbakarkendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='MerkKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merk', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipeKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tipe', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmisiKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_transmisi', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Menunggu Konfirmasi'), ('Dikonfirmasi', 'Dikonfirmasi'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Pending', max_length=20)),
                ('tanggal_reservasi', models.DateTimeField(auto_now_add=True)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_rental.kendaraan')),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='merk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_rental.merkkendaraan'),
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_rental.modelkendaraan'),
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='tipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_rental.tipekendaraan'),
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='transmisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_rental.transmisikendaraan'),
        ),
    ]
