# Generated by Django 4.2.26 on 2025-12-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendaraan',
            name='kapasitas',
            field=models.IntegerField(null=True),
        ),
    ]
