# Generated by Django 4.2.26 on 2026-01-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_rental', '0002_alter_kendaraan_kapasitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
