# Generated by Django 4.2.26 on 2026-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rental', '0003_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_bayar/'),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='lokasi_ambil',
            field=models.CharField(default='Kantor Pusat', max_length=255),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='lokasi_kembali',
            field=models.CharField(default='Kantor Pusat', max_length=255),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='metode_pembayaran',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='order_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('settlement', 'Lunas'), ('expire', 'Kedaluwarsa'), ('cancel', 'Dibatalkan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='tanggal_mulai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='tanggal_selesai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
