# Generated by Django 4.2.26 on 2026-01-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rental', '0004_reservasi_bukti_pembayaran_reservasi_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='order_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
